### ISSUE TITLE
Investigate the possibility of implementing the type class :<: in Coq

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#110]
## Description

It should be investigated whether it is possible to define the [`:<:` type class (p. 26)](https://bunkenburg.net/papers/ModelingCallTimeChoiceAsEffect.pdf)  in Coq.

## Motivation

The Haskell version of the share operator uses a type class `:<:` that consists of a function `inj` to dynamically inject an effect into a combination of effects containing that effect. 
This way, we don't have to rely on the concrete structure of the effect stack when we define functions that require a certain effect  (e.g. the `share` operator, whose argument is required to contain the `Share` effect). 

## Alternatives
An alternative to using `:<:` would be to use a fixed effect stack so the placement of an effect within a combination of effects can be done explicitly. 
However, this will likely lead to a significant loss of flexibility.

## ToDo

- [x] Implement a type class `Injectable` in Coq that represents that a given effect is contained in another given effect (stack).
- [x] Define useful instances of the type class.
- [ ] Add tests to ensure that the correct instance is consistently chosen in situations where more than one instance fits.
