### ISSUE TITLE
Implement effect handlers

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#116]
## Description

Handlers for `Free` programs containing various effects should be implemented.

## Motivation

Programs translated with the Free Compiler produce `Free` values. The semantics of such a program are given by a handler that transforms such a `Free` value into an appropriate data structure (e.g. `option` for `Maybe` or a choice tree for `ND`). 

To test the implementation of sharing and its interaction with other effects, we should define all necessary handlers to fully evaluate an effectful program containing sharing. 

## Dependencies

This issue does not depend on any open issues.

## ToDo

- [x] Implement a handler for a program without effects (`Identity` effect handler)
- [x] Implement a handler for a non-deterministic program (`ND` effect handler)
- [x] Implement a handler for a program containing tracing (`Trace` effect handler)
- [x] Implement a handler to evaluate sharing in combination with non-determinism (`Share` + `ND` handler)
- [x] Implement a handler to evaluate sharing in combination with tracing (`Share` + `Trace` handler)
- [x] Write tests for the handlers.

**Comment by ichistmeinname** [comment]
I'm still in favour of modelling tracing (and partiality) instead of non-determinism. There's no direct need for the non-determinism effect.

**Comment by MajaRet** [comment]
There should be no problem with modelling both, right? Especially because the model for non-determinism already exists. But I'll gladly add the implementation of a `Share` + `Trace` handler to the ToDo list (and an issue to model a `Trace` effect).
