### ISSUE TITLE
Built-in operators evaluate arguments in wrong order

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#133]
### Description

Some built-in operators for `Integer`s from the base library evaluate their arguments in a different order than Haskell.

### Steps to Reproduce

Consider the following expression.

```haskell
error "a" - error "b"
```

#### Expected Behavior

In GHCi the expression above throws the exception `"b"` since `(-)` evaluates its right argument first.

#### Actual Behavior

In Coq the expression above throws the exception `"a"` since the implementation of `subInteger` in the Coq base library binds the left argument first (see [`Integer.v`](https://github.com/FreeProving/free-compiler/blob/6fbac91aae1f55bd84c7b2989a6ce243e57c7a7d/base/coq/Prelude/Integer.v#L38)). The same behavior is shown by `_-_` in the Agda back end (see [`Integer.agda`](https://github.com/FreeProving/free-compiler/blob/6fbac91aae1f55bd84c7b2989a6ce243e57c7a7d/base/agda/Base/Free/Integer.agda#L26)).

### Versions

 - Git commit: 6fbac91aae1f55bd84c7b2989a6ce243e57c7a7d
 - `ghc --version`: 8.6.5
 - `cabal --version`: 3.2.0.0
 - `coqc --version`: 8.11.0
 - OS: Ubuntu 19.10

### Tasks

 - [ ] Use GHCi to investigate in which order Haskell evaluates the arguments of `(&&)`, `(||)`, `(+)`, `(-)`, `(*)`, `(^)`, `(<)`, `(<=)`, `(==)`, `(/=)`, `(>)` and `(>=)`.
 - [ ] Add an `./example` module with QuickCheck properties of the form 
   ```haskell
   prop_op_order :: Property
   prop_op_order = error "a" `op` error "b" === error "…"
   ``` 
   for each operator. If an operator has other interesting behavior regarding the order of evaluation (for example short-circuit evaluation), add a property as well.
 - [ ] Prove the QuickCheck properties in Coq.
 - [ ] Prove the QuickCheck properties in Agda.
 - [ ] Fix the implementation of the operator in the base libraries, if a property does not hold.
