### ISSUE TITLE
Detect effects in functions

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#134]
## Description

We should annotate in the environment whether a function contains an effect or depends on a function that contains that effect. Additionally, a compiler pass should be added that determines which functions contain which effects directly or indirectly.

For details about how that could be done, see @just95's comment below.

## Motivation

In Coq, a function that contains an effect must be given an instance of a corresponding typeclass as an argument. Similarly, functions that depend on such a function also need to be given that instance.
We currently analyze functions for the partiality effect and denote it in the environment via a marker `isPartial`. We should do the same for other supported effects (currently sharing and tracing), and ideally group these analyses together into a single effect analysis pass.

## ToDo (courtesy of @just95)
 - [x] Add `IR.Trace` constructor to [`IR.Expr`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/IR/Syntax/Expr.hs#L18).
 - [x] Add `trace` to the [IR parser](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Frontend/IR/Parser.hs#L577).
 - [x] Add `trace` to the Haskell to IR [`Simplifier`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Frontend/Haskell/Simplifier.hs#L616).
 - [x] Add `Tracing` constructor to [`LIR.Effect`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/LiftedIR/Effect.hs#L9).
 - [x] Replace [`isPartial`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Environment/Entry.hs#L94) by a field of type `[LIR.Effect]`.
    + [x] Update the [encoder](https://github.com/FreeProving/free-compiler/blob/main/src/lib/FreeC/Environment/ModuleInterface/Encoder.hs) and [decoder](https://github.com/FreeProving/free-compiler/blob/main/src/lib/FreeC/Environment/ModuleInterface/Decoder.hs) for module interface files.
    + [x] Document the changes in `./doc/ModuleInterfaceFileFormat.md`.
    + [x] Bump the module interface file format version.
    + [x] Update `Prelude.toml` and `QuickCheck.toml`.
 - [x] Replace [`PartialityAnalysisPass`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Pass/PartialityAnalysisPass.hs) by an `EffectAnalysisPass`.

**Comment by just95** [comment]
> We should annotate in the IR whether a function contains tracing or depends on a function that contains tracing.

The intermediate representation is not the right place for such an annotation. Whether a function requires the the `Trace` effect should be stored in the environment. `hasTracing` is analogous to the [`isPartial` property of `FuncEntry`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Environment/Entry.hs#L94). However, there would have to be an AST node for calls to `trace` similar to [`IR.Undefined` and `IR.ErrorExpr`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/IR/Syntax/Expr.hs#L61).

 - [ ] Add `IR.Trace` constructor to [`IR.Expr`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/IR/Syntax/Expr.hs#L18).
 - [ ] Add `trace` to the [IR parser](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Frontend/IR/Parser.hs#L577).
 - [ ] Add `trace` to the Haskell to IR [`Simplifier`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Frontend/Haskell/Simplifier.hs#L616).

The solution outlined above is not ideal. Since `trace` is built into the language, it cannot be imported from `Debug.Trace`. Thus, I'd suggest to pretend that `trace` is part of the `Prelude` for the time being. In the long run it is desirable to make `undefined`, `error` and `trace` regular functions (and provide a built-in module `Debug.Trace` that exports `trace`). Until `String` literals are supported, that is not possible though.

> Since we need to do very similar passes to annotate sharing (as let bindings) and partiality, it might make sense to group these passes together in some way.

I agree that there should be a common abstraction for partiality and tracing that also allows us to add more effects in the future. I suggest to do the following.

 - [ ] Add `Tracing` constructor to [`LIR.Effect`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/LiftedIR/Effect.hs#L9).
 - [ ] Replace [`isPartial`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Environment/Entry.hs#L94) by a field of type `[LIR.Effect]`.
    + [ ] Update the [encoder](https://github.com/FreeProving/free-compiler/blob/main/src/lib/FreeC/Environment/ModuleInterface/Encoder.hs) and [decoder](https://github.com/FreeProving/free-compiler/blob/main/src/lib/FreeC/Environment/ModuleInterface/Decoder.hs) for module interface files.
    + [ ] Document the changes in `./doc/ModuleInterfaceFileFormat.md`.
    + [ ] Bump the module interface file format version.
    + [ ] Update `Prelude.toml` and `QuickCheck.toml`.
 - [ ] Replace [`PartialityAnalysisPass`](https://github.com/FreeProving/free-compiler/blob/bb31c765bad641d45f28d73d89fe54f225c3baeb/src/lib/FreeC/Pass/PartialityAnalysisPass.hs) by an `EffectAnalysisPass`.

**Comment by MajaRet** [comment]
Oh, of course you're right, thank you! I'll replace the bullet points.

**Comment by just95** [comment]
See also #179 for the implementation of the `EffectAnalysisPass` and the addition of a `[LIR.Effect]` field.
