### ISSUE TITLE
Implement Normalform typeclass

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#148]
## Description

Implement a typeclass `Normalform` to pull effects into the outermost layer before handling a program.

## Motivation

TBA

## ToDo

- [ ] Implement a `Normalform` typeclass.
- [ ] Implement `Normalform` instances for pre-defined data types.
- [ ] Normalize programs before handling them in the test module.
- [ ] Add appropriate tests to the sharing handler test suite.
