### ISSUE TITLE
Implement ShareableArgs typeclass

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#149]
## Description

Implement deep sharing via a typeclass `ShareableArgs` to share arguments when using `cbneed`.

## Motivation

TBA

## Dependencies

This issue does not depend on any open issues.

## ToDo

- [ ] Implement a `ShareableArgs` typeclass.
- [ ] Implement `ShareableArgs` instances for pre-defined data types.
- [ ] Add sharing of arguments and a `ShareableArgs` constraint to `cbneed`.
- [ ] Add tests for deep sharing to the sharing handler tests.
