### ISSUE TITLE
Implement error effect in Coq

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#18]
## Description

Add a container instance that allows us to model computations in the [`Error`](https://github.com/FreeProving/free-compiler/blob/master/base/Free/Instance/Error.v)  monad to the `base` library.

## Motivation

Currently the `base` librarary contains `Container` instances for the [`Maybe`](https://github.com/FreeProving/free-compiler/blob/master/base/Free/Instance/Maybe.v) and [`Identity`](https://github.com/FreeProving/free-compiler/blob/master/base/Free/Instance/Identity.v) monads. Partial functions require an instance of the [`Partial`](https://github.com/FreeProving/free-compiler/blob/master/base/Free/Partial.v) type class. `Maybe` is the only instance of this type class at the moment.
However, sometimes the user wants to show that a specific error cannot occur or that only specific errors occur in their program. For this purpose, the `Maybe` monad is not sufficient since the `Nothing` constructor carries no information about the concrete error.
The `base` library contains a template for the [`Error`](https://github.com/FreeProving/free-compiler/blob/master/base/Free/Instance/Error.v) monad already but is currently not implemented.
The goal is to implement the `Error` monad such that it can be used as an alternative to `Maybe`.

## Tasks

 - [x] Add suitable definitions for `Shape` and `Pos` to `Error.v`.
 - [x] Implement the `Partial` type class for your definitions of `Shape` and `Pos`.
 - [x] Add an example for how to use the `Error` monad in proofs to the `example` directory.

## Getting Started

Have a look at the [accompanying code](https://github.com/FreeProving/free-proving-code) from the publication [One Monad to Prove Them All](https://arxiv.org/abs/1805.08059).
