### ISSUE TITLE
Adapt sharing infrastructure to flexible strategy approach

### ISSUE THREAD

**Issue by MajaRet** [FreeProving/free-compiler#183]
## Description

Add another operation `call :: forall (A : Type), Free Shape Pos A -> Free Shape Pos (Free Shape Pos A)` to the `Shareable` class and add a `Cbv` instance for `Shareable`.
Since the `Shareable` class actually determines the evaluation strategy, it should also be renamed to `Strategy`.

## Motivation

We do not want to choose the modeled evaluation strategy at compile time, but want to enable the user to prove properties about the evaluation of their code for any of the provided strategies (call-by-value, call-by-name, call-by-need). 

To model call-by-value correctly, we need to introduce let bindings for every non-variable expression in a program. These let bindings are translated to the `share` operator.
However, in a call-by-need setting, the `share` operator introduces sharing syntax every time it is used - even when nothing is shared -, which will likely compliclate proofs.
Therefore, we introduce a second operator `call`, which does not introduce sharing syntax. 
The compiler will [analyze](https://github.com/FreeProving/free-compiler/pull/169) where values are actually shared and translate those `let` bindings into `share`s, the others into `call`s.

## ToDo

- [x] Rename the typeclass `Shareable` to `Strategy`.
- [x] Add a function `call` to the `Strategy` typeclass.
- [x] Add a `Strategy` instance `Cbv` for call-by-value evaluation.
