### ISSUE TITLE
Remove `Maybe` from `Environment` entries

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#19]
## Description

The `entryArgTypes` and `entryReturnType` fields of the [`EnvEntry`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-Entry.html#t:EnvEntry) data type should contain `IR.Type`s instead of `Maybe IR.Type`s.

## Motivation

The`entryArgTypes` and `entryReturnType` fields  had to be lifted to the  `Maybe` monad because the environment contains entries for generated helper functions but not all of their argument and return types were known. Since the compiler supports type inference now, we also know the types of helper functions. Thus, it should be possible to remove `Maybe` from those two fields.

## Tasks

 - [x] Update the `EnvEntry` data type.
 - [x] Fix resulting type errors.
 - [x] Investigate whether the compiler generates untyped AST nodes after type inference.
 - [x] If there are such untyped nodes, update the code such that their type is properly annotated.

**Comment by stu204767** [comment]
I have two questions about this issue:
1. The `EnvEntry` data type contains `entryArgTypes` and `entryReturnType` fields for both the `ConEntry` and the `FuncEntry` constructor. Should I remove `Maybe` from all four fields or just from the two fields belonging to the `FuncEntry` constructor?
2. At some points in the code, for example in the function `defineFuncDecl` in the module `FreeC.Pass.DefineDeclPass`, values from the `IR.FuncDecl` data type are assigned to the `entryArgTypes` and `entryReturnType` fields. Those values are encapsulated in the `Maybe` type. Should I use `fromJust` to convert them or remove `Maybe` from `IR.FuncDecl` as well?

**Comment by just95** [comment]
> Should I remove `Maybe` from all four fields or just from the two fields belonging to the `FuncEntry` constructor?

`Maybe` has to be removed from all four fields. In Haskell it would be invalid to have two fields with the same name but different types.

```haskell
data Foo = Bar { a :: String } | Baz { a :: Integer }
```

```
example/Foo.hs:3:1: error:
    • Constructors Bar and Baz give different types for field ‘a’
    • In the data type declaration for ‘Foo’
  |
3 | data Foo = Bar { a :: String } | Baz { a :: Integer }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

> Should I use `fromJust` to convert them or remove `Maybe` from `IR.FuncDecl` as well?

`Maybe` must not be removed from `IR.FuncDecl`. The type information is not present prior to type inference. Using `fromJust` should be fine since environment entries are created after type inference. I'm not sure whether the compiler adds untyped AST nodes after type inference (that's why there are the last two tasks).
