### ISSUE TITLE
Name conflict between imported modules

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#20]
### Description

The compiler usually renames identifiers during the translation to Coq. When the same identifier is used in two different modules, they are not renamed. Importing both modules can lead to a name conflict in Coq.

### Steps to Reproduce

1. Consider two Haskell modules

    ```haskell
    module A where
    data Foo = Bar

    module B where
    data Bar = Foo
    ```

   and compile them using the following command.

    ```bash
    freec -o generated A.hs B.hs 
    ```

    The identifiers `Foo` and `Bar` are not renamed by `freec` because there are no name conflicts when the individual modules are defined in Coq.

2. Now consider the following Haskell module that imports the two other modules.

    ```haskell
    module C where

    import A
    import B

    mkFoo :: Foo
    mkFoo = Bar

    mkBar :: Bar
    mkBar = Foo
    ```

    In Haskell there are no name conflicts because the namespaces for types and values are separated.

3. Compile the importing module as follows.

     ```bash
     freec -o generated C.hs 
     ```

#### Expected behavior

There should be no name conflicts in the generated Coq code for `C.hs`.

#### Actual behavior

The following Coq code is generated for `mkFoo`.

```coq
Definition mkFoo (Shape : Type) (Pos : Shape -> Type)
   : Free Shape Pos (Foo Shape Pos) :=
  Bar Shape Pos.
```

In Coq there is no distinction between the namespaces of values and types. Thus, the identifiers `Foo` and `Bar` are ambigious. Since `B` is imported after `A`, `Foo` and `Bar` refer to `B.Foo` and `B.Bar` respectively. However, in Haskell they refer to `A.Foo` and `A.Bar`.

### Versions

 - `freec --version`: `The Free Compiler, version 0.1.0.0 (v0.1.0.0-549-g8665b41, ghc 8.6, linux, x86_64)`
 - `ghc --version`: `8.6.5`
 - `cabal --version`: `2.4.1.0`
 - `coqc --version`: `8.11.0`
 - OS: Ubuntu 19.10

### Tasks

In order to fix this bug and avoid similar bugs in the future, all identifiers should be explicitly qualified in Coq.

 - [x] Try to find more examples where name conflicts can occur in Coq due to imports.
 - [ ] Add (failing) test cases for the examples.
 - [x] Adapt the translation of `import` declarations such that external identifiers must be qualified in Coq.
 - [ ] Qualify Coq identifiers of [environment entries](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-Entry.html) when the [module interface](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-ModuleInterface.html) is imported or exported.
