### ISSUE TITLE
Add check for complete pattern matching

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#21]
## Description

The compiler should report an error if a `case` expression does not contain exactly one alternative for every constructor of the matched data type.

## Motivation

One assumption of the compiler is that pattern matching is complete, i.e., there is one alternative for every constructor of the matched data type in a `case` expression. If the [pattern-matching compiler](https://github.com/FreeProving/haskell-src-transformations/) is enabled, the `case` completion phase will add missing alternatives. However, pattern-matching compilation is optional and even if it is enabled, there are [known bugs](https://github.com/FreeProving/haskell-src-transformations/issues/7) in the pattern-matching compiler that cause the generation of code that violates the assumption. Since the compiler does not check the assumption, the generated Coq code is invalid if the assumption is not met. For a user it may be difficult to understand the error reported by Coq. Thus, a check should be implemented into the Free Compiler directly.

## Tasks

 - [x] Add a field to [environment entries for data type declarations](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-Entry.html#v:DataEntry) with the names of its constructors.
     + [x] Update the [encoder](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-ModuleInterface-Encoder.html) and [decoder](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-ModuleInterface-Decoder.html) for module interface files accordingly. 
     + [x] Don't forget to bump the module interface file format  version number.
     + [x] Identify where such entries are added to the environment and initialize the new field appropriatly.
 - [x] Add a compiler [`Pass`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Pass.html#t:Pass) to the compiler [`pipeline`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Pipeline.html#v:pipeline) that performs the check. Perform at least the following checks and report a fatal error if any check fails.
    + [x] The type of the `case` expression's scrutinee is a data type (i.e., not a function).
    + [x] There is one alternative for every constructor of the data type.
    + [x] There are not multiple alternatives for the same constructor of the data type.
 - [x] Add documentation and test cases for your compiler `Pass`.
