### ISSUE TITLE
Add check for kinds of type expressions

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#22]
## Description

The compiler should report an error if a type constructor is applied to the wrong number of arguments or a type variable is applied to any type arguments.

## Motivation

The compiler currently only supports type variables of [kind](https://wiki.haskell.org/Kind) `*`. If type variables of other kinds were supported, we would have to implement a mechanism to infer the kinds of type variables. Therefore, it is currently not allowed to write a type like `m a` for example. However, the compiler does not check whether a type variable is actually never applied at the moment. In consequence, generated Coq code may contain type errors if the input program contains such a type variable application. For a user it may be difficult to understand the error reported by Coq. Thus, a check should be implemented into the Free Compiler that produces a better error message.

A consequence of the restriction above is that every type constructor has a kind of the form `* -> κ`, i.e., the arguments of all type constructors must be types not type constructors themselves. Therefore, a type expression must contain fully applied type constructors only since it could neither be used as a type nor passed as a type argument otherwise. Whether this requirement is met by the input program should be checked by the compiler as well.

## Tasks

- [x] Add a compiler [`Pass`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Pass.html#t:Pass) to the compiler [`pipeline`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Pipeline.html#v:pipeline) that performs the check. Perform at least the following checks and report a fatal error if any check fails.
    - [x] Type variables do not occur on the left-hand side of type applications.
    - [x] Every `n`-ary type constructor is applied to exactly `n` type arguments.
 - [x] Add documentation and test cases for your compiler `Pass`.
