### ISSUE TITLE
Add bang patterns to IR

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#23]
## Description

By adding abstractions inspired by GHC's [`BangPatterns`](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/glasgow_exts.html#extension-BangPatterns) language extension to the intermediate representation (IR), the translation of recursive functions to Coq can be simplified.

## Motivation

The `Environment` currently contains a field [`envDecArgs`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment.html#v:envDecArgs). This field is used for two purposes.

 1. If the input module contains a function declaration

     ```haskell
     f x₁ … xᵢ … xₙ = e
     ```

     and one of the following pragmas 

     ```haskell
     {-# FreeC f DECREASES ON xᵢ #-}
     {-# FreeC f DECREASES ON ARGUMENT i #-}
     ```

     the `envDecArgs` map contains an entry that maps the name of `f` to `(i, "xᵢ")`. This information is used by [`identifyDecArgs`](https://freeproving.github.io/free-compiler/docs/master/FreeC-Backend-Coq-Analysis-DecreasingArguments.html#v:identifyDecArgs) to skip termination checking for `f` and assume `xᵢ` is its decreasing argument.

 2. Regardless of whether there is such an annotation for the decreasing argument or not, the result of `identifyDecArgs` is used to [split recursive functions](https://github.com/FreeProving/free-compiler/blob/010fba5d414a9184be056c30f6ced8bd7f1629ac/src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs#L77) into helper and main functions. The `envDecArgs` field is manipulated such that the resulting non-recursive main function does not have an entry anymore (if one was added by a pragma before) and an entry is added for each recursive helper function. This information is used during the [translation of function applications](https://github.com/FreeProving/free-compiler/blob/010fba5d414a9184be056c30f6ced8bd7f1629ac/src/lib/FreeC/Backend/Coq/Converter/Expr.hs#L109) to insert a bind operation for calls to helper functions.

That `envDecArgs` has multiple purposes is not a good design decision and the management of the decreasing argument map that has to be performed in the second step is quite complicated and prone to errors . Thus, the goal is to get rid of the second use case.

What we actually want to do in the second use case is to mark that the helper functions is strict in its decreasing argument. In Haskell there is actually a way to express that a function is strict in specific arguments using the [`BangPatterns`](https://downloads.haskell.org/~ghc/8.6.5/docs/html/users_guide/glasgow_exts.html#extension-BangPatterns) language extension. If the IR supported bang patterns for function declarations, they could be used to model the strictness of helper functions.

## Tasks

 - [x] Add bang patterns to the IR.
    + [x] Extend the IR AST.
    + [x] Extend the IR parser.
    + [x] Extend the IR pretty-printer.
 - [x] Add information about strict arguments to [function environment entries](https://freeproving.github.io/free-compiler/docs/master/FreeC-Environment-Entry.html#v:FuncEntry).
 - [x] Update the translation of function applications and other translation rules.
 - [x] Remove uses of `envDecArgs` which are not related to the first use case.

> **Note:** The goal is to add bang patterns to IR not to add bang pattern support to the Haskell front end. `BangPatterns` are a Haskell language extension and will thus not supported by `freec`. However, don't focus on recursive functions in your test cases. Test you implementation with bang patterns in arbitrary positions. Most importantly, bang patterns should also be supported in `case` expressions.
