### ISSUE TITLE
Compare Agda representations

### ISSUE THREAD

**Issue by JonasHoefer** [FreeProving/free-compiler#49]
# Description 
The Agda compiler [package](https://github.com/agda/agda), which we have chosen as basis for generating Agda code contains multiple representation for Code. Compare the representations and decide which to use.
We were advised against the `concrete` representation. For the `internal` and `abstract` representation do the following.

# Tasks
- [x] Import the monad for the conversion algorithms 
- [ ] Generate some simple terms
- [ ] Outline the renaming/name generation process for the different representations

**Comment by JonasHoefer** [comment]
We ran into problems working with both representations. To pretty print terms they are converted into the `Concrete` representation. The conversion algorithm generates `syntax` and `postulate` declarations in the `Concrete` representation for type declarations in the `Abstract` one. This doesn't seem to be intended behaviour. Furthermore the algorithm forces use to work in Agda's compiler intern `TCM` monad (`IO` + `State` we have to setup).
The `Abstract` representation could allow us to typ check generated Code, but at the moment this isn't a priority.
