### ISSUE TITLE
Parameterize IR modules over their contents

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#71]
## Description

The [`IR.Module`](https://freeproving.github.io/free-compiler/docs/master/FreeC-IR-Syntax-Module.html#t:Module) data type should be expressed in terms of a polymorphic data type that is parameterized over a data type that determines the contents of the module.

```haskell
data ModuleOf contents = ModuleOf { …, modContents :: contents }
data IR.TopLevelDecl = …
type Module = ModuleOf [TopLevelDecl]
```

## Motivation

Dependency analysis currently has to be performed in multiple places of the compiler (for example, [in the compiler passes](https://github.com/FreeProving/free-compiler/blob/master/src/lib/FreeC/Pass/DependencyAnalysisPass.hs) and [in the back end](https://github.com/FreeProving/free-compiler/blob/1b666387fe35fca42652471b6e46c8d3f1305c03/src/lib/FreeC/Backend/Coq/Converter/FuncDecl.hs#L19)). This is mainly because the information about strongly connected components of the dependency graph cannot be stored within `IR.Module`s. In order to perform dependency analysis only once, lists of `DependencyComponent`s have to be stored in `IR.Module`s instead of lists of declarations after dependency analysis has been performed. In this first step, the AST should be extended to allow for such a generalization of dependency analysis in the future. 

In theory it would work to parameterize `IR.Module` over a component data type (i.e., `Identity` for the current behavior and `DependencyComponent` for the analysed modules). However, it would be more flexible if we move the entire contents of the module (i.e., everything except for it's name and `SrcSpan`) into a parameter.
I'd recommend to add a new polymorphic data type `IR.ModuleOf contents` and express `IR.Module` in terms of this new data type. `IR.ModuleOf IR.FuncDecl` should represent a module that contains a single function declaration, for example.

Most of the existing code should not be affected by this change. Apart of `FreeC.IR.Syntax.Module`, I expect that only code that uses record updates to overwrite module contents has to be changed.

## Tasks

 - [x] Add a polymorphic data type `IR.ModuleOf contents`.
 - [x] Add a data type `IR.TopLevelDecl` for all declarations that can occur on top-level of IR modules with record fields and predicates for each constructor.
 - [x] Express `IR.Module` in terms of `IR.ModuleOf [IR.TopLevelDecl]`.
 - [x] Express getters for content fields (i.e., `IR.modImports` through `IR.modFuncDecls`) of `IR.Module` using `map` and `filter`.
 - [x] Replace uses of record updates for `IR.Module` with the more general record updates for `IR.ModuleOf`.
