### ISSUE TITLE
Invoke passes from `Main` module

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#97]
## Description

The invocation of the [compiler pipeline](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/Pipeline.hs#L27)  should be moved from [`convertModule`](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/Backend/Coq/Converter/Module.hs#L28) to the command line interface in [`Main.hs`](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/exe/Main.hs#L125).

## Motivation

The compiler `Pass`es are currently invoked in the Coq back end during the conversion of modules. This is mainly the case because both the passes and the conversion have to be performed in the same [`moduleEnv`](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/Monad/Converter.hs#L190). Since we want to add support for more back ends and the compiler pipeline must be executed before each back end, the `Pass`es should be executed before `convertModule` is invoked in `Main.hs`.

## Tasks

Do the following on the `main` branch.

 - [x] Call `runPipeline` in `Main.hs`.
 - [x] Rename `convertModule'` to `convertModule` in the [Coq back end](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/Backend/Coq/Converter/Module.hs#L28).

Do the following on the `dev-agda` branch.

 - [x] Merge the `main` branch (or the feature branch for this issue).
 - [x] Rename `convertModule'` to `convertModule` in the [Agda back end](https://github.com/FreeProving/free-compiler/blob/dev-agda/src/lib/FreeC/Backend/Agda/Converter/Module.hs).
