### ISSUE TITLE
Add abstractions for front end and back end

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#98]
## Description

Add data types that abstract from front ends and back ends. A front end basically maps [`SrcFile`s](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/IR/SrcSpan.hs#L36) to [`IR.Module`s](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/lib/FreeC/IR/Syntax/Module.hs#L18). A back end on the other hand maps `IR.Module`s to the source code in the target language (could be a `String` or also a `SrcFile` for example). Additionally, the data type should provide mechanisms for the generation of back end specific files such as `_CoqProject`. Select an appropriate monad and add additional information such as a name, description, file extension etc. to the data type as you see fit.

## Motivation

Since we want to add command line options to select different front ends and back ends, we have to abstract from the concrete front end or back end in `Main`. In this first step, we want to lay the ground work for such command line options. To test the abstractions, pseudo front and back ends should be added for the intermediate representation (IR) which just parse and pretty print, respectively. These pseudo front and back ends will also improve debugging of the Free Compiler by allowing us to control the IR that is plugged into the pipeline and seeing the IR after all passes have been applied.

## Tasks

Do the following on the `main` branch.

 - [x] Add modules `FreeC.Backend` and `FreeC.Frontend`.
 - [x] Add the data types described above to the corresponding modules.
 - [x] Add instance of the front end data type for the Haskell front end.
 - [x] Add instance of the back end data type for the Coq front end.
 - [x] Add a list or map of available back ends / front ends to the modules.

Do the following on the `dev-agda` branch.

 - [x] Merge the `main` branch (or the feature branch for this issue).
 - [x] Add an instance of the back end data type for the Agda back end.
