### ISSUE TITLE
Add `--from` and `--to` command line options

### ISSUE THREAD

**Issue by just95** [FreeProving/free-compiler#99]
## Description

Add `--from LANG` and `--to LANG` command line options to the command line interface to select front end and back end.
Both command line options should be optional. `--from` should default to `haskell` and `--to` should default to `coq`.

For example, the following command should behave like the current version of `freec` without additional command line options.

```bash
freec --from haskell --to coq example/Data/List.hs
```

The following command should dump the intermediate representation (IR) produced by the compiler pipeline on the other hand by using the IR *pseudo* back end added in #98.

```bash
freec --to ir example/Data/List.hs
```

## Motivation

We want to add additional front ends (e.g. `ghc-lib`) and back ends (e.g. `agda`) in the future. In order to switch the front end or back end, command line options have to be added.

## Tasks

 - [x] Add fields for the selected front end and back end to [`Option`](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/exe/FreeC/Application/Options.hs#L13).
 - [x] Add descriptors for the command line options to [`optionDescriptors`](https://github.com/FreeProving/free-compiler/blob/6864d3b5a33b1b1206b355a9b3b62618605d99db/src/exe/FreeC/Application/Options/Descriptors.hs#L11).
 - [x] Use the abstractions provided by #98 in `Main`.
 - [x] Select the appropriate front end or back end based on the command line options. Provide user friendly error messages if there is no such front end or back end. 
 - [x] Add documentation for `--from` and `--to` to the README and add an entry to the *unreleased* section of the CHANGELOG.
